services:
  postgres:
    image: postgres
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: example

  pulsar:
    image: apachepulsar/pulsar:latest
    container_name: pulsar
    command: bin/pulsar standalone
    ports:
      - "6650:6650"
      - "8080:8080"
    volumes:
      - pulsar-data:/pulsar/data
      - pulsar-conf:/pulsar/conf

volumes:
  pulsar-data:
  pulsar-conf: